### ISSUE TITLE
sdist is missing tox.ini

### ISSUE THREAD

**Issue by mtelka** [adamchainz/time-machine#359]
### Package Version

2.10.0

### Description

The sdist package at PyPI is missing `tox.ini`.  Please add the missing file to sdist to make downstream testing easier.  Thank you.

**Comment by adamchainz** [comment]
Sorry, the tests were never meant to be in the sdist. I accidentally added them in #245. I don't support running the tests outside of pulling the whole repository and running `tox`, because it's too much busywork to document and provide fixes for other test environments. Test file removed from the sdist in #362.
