### ISSUE TITLE
Please release a new version with the latest dateutil

### ISSUE THREAD

**Issue by kbaikov** [adamchainz/time-machine#426]
### Python Version

3.12

### pytest Version

8

### Description

The python-dateutil was updated recently to version 2.9.0 https://github.com/dateutil/dateutil/releases
Which fixed the py312 Warning call to `datetime.utcfromtimestamp`

Since the dateutil is unpinned in your requirements.in could you please pip-compile and make a new release?

Possible also removing the `-W ignore:datetime.datetime.utcnow:DeprecationWarning ` from the tox.ini file.

THanks!

**Comment by adamchainz** [comment]
The `requirements/` directory is only used during tests. It does not apply to you as a user of the package.

The for-users requirement is declared in `pyproject.toml` here: https://github.com/adamchainz/time-machine/blob/8d4c9c078f00f761a676012ad984e01622c7e9ed/pyproject.toml#L42 . It is not pinned.

If you’re talking about the warning from #424, I’m just releasing the fix for that now.
